
using System;
using Gtk;
using DomainCore;

namespace PropertyManager
{
    
    /// <summary>
    /// Dialog class to display SQL statements.
    /// </summary>
    public partial class BufferDisplayDlg : Gtk.Dialog
    {

        /// <summary>
        /// Wrapper class for the TextView control to handle the
        /// vagaries of displaying SQL.
        /// </summary>
        private MonospacedTextViewControl textview;

        /// <summary>
        /// Constructs a new BufferDisplayDlg object.
        /// </summary>
        public BufferDisplayDlg()
        {
            this.Build();

            textview = new MonospacedTextViewControl(textViewMain);
        }

        /// <summary>
        /// Displays the dialog as modal and populates the text view
        /// with the SQL generated by the domain object.
        /// </summary>
        /// <param name="parentWindow">
        /// The parent of the window.
        /// </param>
        /// <param name="domain">
        /// The domain object to display the SQL for.
        /// </param>
        /// <returns>
        /// <c>true</c> if the OK button was pressed.
        /// </returns>
        public bool DoModal(Window parentWindow, Domain domain)
        {
            bool ok = false;

            TransientFor = parentWindow;

            string sql = domain.SaveSQL();

            textview.TagText("Monospaced", sql);

            int response = Run();
            if (response == Gtk.ResponseType.Ok.value__)
            {
                ok = true;
            }

            Destroy();

            return ok;
        }
    }
}
