// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ControlWrappers {
    
    
    public partial class CronValueEditor {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.Action selectAllAction;
        
        private Gtk.Action clearAction;
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow scrolledwindow2;
        
        private Gtk.TreeView tvList;
        
        private Gtk.Toolbar toolbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ControlWrappers.CronValueEditor
            Stetic.BinContainer w1 = Stetic.BinContainer.Attach(this);
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            this.selectAllAction = new Gtk.Action("selectAllAction", null, null, "gtk-select-all");
            w2.Add(this.selectAllAction, null);
            this.clearAction = new Gtk.Action("clearAction", null, null, "gtk-clear");
            w2.Add(this.clearAction, null);
            this.UIManager.InsertActionGroup(w2, 0);
            this.Name = "ControlWrappers.CronValueEditor";
            // Container child ControlWrappers.CronValueEditor.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.scrolledwindow2 = new Gtk.ScrolledWindow();
            this.scrolledwindow2.CanFocus = true;
            this.scrolledwindow2.Name = "scrolledwindow2";
            this.scrolledwindow2.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow2.Gtk.Container+ContainerChild
            this.tvList = new Gtk.TreeView();
            this.tvList.CanFocus = true;
            this.tvList.Name = "tvList";
            this.tvList.EnableSearch = false;
            this.tvList.HeadersVisible = false;
            this.scrolledwindow2.Add(this.tvList);
            this.vbox2.Add(this.scrolledwindow2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow2]));
            w4.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.UIManager.AddUiFromString("<ui><toolbar name='toolbar1'><toolitem name='selectAllAction' action='selectAllAction'/><toolitem name='clearAction' action='clearAction'/></toolbar></ui>");
            this.toolbar1 = ((Gtk.Toolbar)(this.UIManager.GetWidget("/toolbar1")));
            this.toolbar1.Name = "toolbar1";
            this.toolbar1.ShowArrow = false;
            this.toolbar1.ToolbarStyle = ((Gtk.ToolbarStyle)(2));
            this.toolbar1.IconSize = ((Gtk.IconSize)(3));
            this.vbox2.Add(this.toolbar1);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.vbox2[this.toolbar1]));
            w5.Position = 1;
            w5.Expand = false;
            w5.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            w1.SetUiManager(UIManager);
            this.Hide();
            this.selectAllAction.Activated += new System.EventHandler(this.SelectAllActivated);
            this.clearAction.Activated += new System.EventHandler(this.ClearActivated);
            this.tvList.CursorChanged += new System.EventHandler(this.TreeListCursorChanged);
        }
    }
}
