// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ControlWrappers {
    
    
    public partial class BoundCalendar {
        
        private Gtk.VBox vbox1;
        
        private Gtk.Calendar calBound;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Label lblHour;
        
        private Gtk.SpinButton sbHour;
        
        private Gtk.Label lblMinute;
        
        private Gtk.SpinButton sbMinute;
        
        private Gtk.CheckButton cbNullDateTime;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget ControlWrappers.BoundCalendar
            Stetic.BinContainer.Attach(this);
            this.Name = "ControlWrappers.BoundCalendar";
            // Container child ControlWrappers.BoundCalendar.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.calBound = new Gtk.Calendar();
            this.calBound.CanFocus = true;
            this.calBound.Name = "calBound";
            this.calBound.DisplayOptions = ((Gtk.CalendarDisplayOptions)(35));
            this.vbox1.Add(this.calBound);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.calBound]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.lblHour = new Gtk.Label();
            this.lblHour.Name = "lblHour";
            this.lblHour.LabelProp = Mono.Unix.Catalog.GetString("H:");
            this.hbox1.Add(this.lblHour);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.lblHour]));
            w2.Position = 0;
            w2.Expand = false;
            w2.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.sbHour = new Gtk.SpinButton(0, 23, 1);
            this.sbHour.CanFocus = true;
            this.sbHour.Name = "sbHour";
            this.sbHour.Adjustment.PageIncrement = 10;
            this.sbHour.ClimbRate = 1;
            this.sbHour.Numeric = true;
            this.hbox1.Add(this.sbHour);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.sbHour]));
            w3.Position = 1;
            w3.Expand = false;
            w3.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.lblMinute = new Gtk.Label();
            this.lblMinute.Name = "lblMinute";
            this.lblMinute.LabelProp = Mono.Unix.Catalog.GetString("M:");
            this.hbox1.Add(this.lblMinute);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.hbox1[this.lblMinute]));
            w4.Position = 2;
            w4.Expand = false;
            w4.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.sbMinute = new Gtk.SpinButton(0, 59, 1);
            this.sbMinute.CanFocus = true;
            this.sbMinute.Name = "sbMinute";
            this.sbMinute.Adjustment.PageIncrement = 10;
            this.sbMinute.ClimbRate = 1;
            this.sbMinute.Numeric = true;
            this.hbox1.Add(this.sbMinute);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox1[this.sbMinute]));
            w5.Position = 3;
            w5.Expand = false;
            w5.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.cbNullDateTime = new Gtk.CheckButton();
            this.cbNullDateTime.CanFocus = true;
            this.cbNullDateTime.Name = "cbNullDateTime";
            this.cbNullDateTime.Label = "";
            this.cbNullDateTime.Active = true;
            this.cbNullDateTime.DrawIndicator = true;
            this.cbNullDateTime.UseUnderline = true;
            this.hbox1.Add(this.cbNullDateTime);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox1[this.cbNullDateTime]));
            w6.Position = 4;
            this.vbox1.Add(this.hbox1);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Hide();
            this.calBound.DaySelected += new System.EventHandler(this.CalendarDaySelected);
            this.calBound.DaySelectedDoubleClick += new System.EventHandler(this.CalendarDaySelectedDoubleClick);
            this.sbHour.ValueChanged += new System.EventHandler(this.HourValueChanged);
            this.sbMinute.ValueChanged += new System.EventHandler(this.MinuteValueChanged);
            this.cbNullDateTime.Toggled += new System.EventHandler(this.NullDateTimeToggled);
        }
    }
}
