// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PropertyManager {
    
    
    public partial class DynPropEntryDlg {
        
        private Gtk.UIManager UIManager;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table2;
        
        private ControlWrappers.BoundComboBox cbApplication;
        
        private ControlWrappers.BoundComboBox cbForm;
        
        private ControlWrappers.BoundComboBox cbProperty;
        
        private Gtk.Label lblApplication;
        
        private Gtk.Label lblDefaultValue;
        
        private Gtk.Label lblProperty;
        
        private Gtk.Label lblQualifier;
        
        private ControlWrappers.BoundEntry txtDefaultValue;
        
        private ControlWrappers.BoundEntry txtQualifier;
        
        private Gtk.Table table3;
        
        private Gtk.HButtonBox btnBoxApplySettings;
        
        private Gtk.HButtonBox hbuttonbox2;
        
        private Gtk.Button btnAddItem;
        
        private Gtk.Button btnRemove;
        
        private Gtk.Label lblEffectiveValues;
        
        private Gtk.Notebook nbValuePages;
        
        private Gtk.Label label2;
        
        private Gtk.Label label1;
        
        private Gtk.Table table4;
        
        private ControlWrappers.BoundCalendar calEndDate;
        
        private ControlWrappers.BoundCalendar calStartDate;
        
        private Gtk.Label lblEndDate;
        
        private Gtk.Label lblStartDate;
        
        private Gtk.Label label6;
        
        private Gtk.Table table5;
        
        private Gtk.Label lblCriteria;
        
        private Gtk.Label lblDays;
        
        private Gtk.Label lblDOWs;
        
        private Gtk.Label lblHours;
        
        private Gtk.Label lblMinutes;
        
        private Gtk.Label lblMonths;
        
        private Gtk.Label lblValue;
        
        private ControlWrappers.CronValueEditor tvDays;
        
        private ControlWrappers.CronValueEditor tvDaysOfWeek;
        
        private ControlWrappers.CronValueEditor tvHours;
        
        private ControlWrappers.CronValueEditor tvMinutes;
        
        private ControlWrappers.CronValueEditor tvMonths;
        
        private ControlWrappers.BoundEntry txtCriteria;
        
        private ControlWrappers.BoundEntry txtValue;
        
        private Gtk.Label label7;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TreeView tvEffectiveValues;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PropertyManager.DynPropEntryDlg
            this.UIManager = new Gtk.UIManager();
            Gtk.ActionGroup w1 = new Gtk.ActionGroup("Default");
            this.UIManager.InsertActionGroup(w1, 0);
            this.AddAccelGroup(this.UIManager.AccelGroup);
            this.Name = "PropertyManager.DynPropEntryDlg";
            this.Title = Mono.Unix.Catalog.GetString("Dynamic Property Details");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Resizable = false;
            this.AllowGrow = false;
            this.HasSeparator = false;
            // Internal child PropertyManager.DynPropEntryDlg.VBox
            Gtk.VBox w2 = this.VBox;
            w2.Name = "dialog1_VBox";
            w2.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table2 = new Gtk.Table(((uint)(4)), ((uint)(3)), false);
            this.table2.Name = "table2";
            this.table2.RowSpacing = ((uint)(6));
            this.table2.ColumnSpacing = ((uint)(6));
            // Container child table2.Gtk.Table+TableChild
            this.cbApplication = new ControlWrappers.BoundComboBox();
            this.cbApplication.Events = ((Gdk.EventMask)(256));
            this.cbApplication.Name = "cbApplication";
            this.cbApplication.CollectionName = "Applications";
            this.cbApplication.LabelAttributeName = "Name";
            this.cbApplication.ValueAttributeName = "Id";
            this.cbApplication.AttributeName = "ApplicationId";
            this.cbApplication.ContextName = "DialogContext";
            this.cbApplication.DomainName = "DynamicProperty";
            this.table2.Add(this.cbApplication);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table2[this.cbApplication]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.cbForm = new ControlWrappers.BoundComboBox();
            this.cbForm.WidthRequest = 250;
            this.cbForm.Events = ((Gdk.EventMask)(256));
            this.cbForm.Name = "cbForm";
            this.cbForm.CollectionName = "Forms";
            this.cbForm.LabelAttributeName = "Description";
            this.cbForm.ValueAttributeName = "Id";
            this.cbForm.ContextName = "DialogContext";
            this.table2.Add(this.cbForm);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table2[this.cbForm]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.LeftAttach = ((uint)(2));
            w4.RightAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(0));
            w4.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table2.Gtk.Table+TableChild
            this.cbProperty = new ControlWrappers.BoundComboBox();
            this.cbProperty.Events = ((Gdk.EventMask)(256));
            this.cbProperty.Name = "cbProperty";
            this.cbProperty.CollectionName = "PropertyDefinitions";
            this.cbProperty.LabelAttributeName = "Name";
            this.cbProperty.ValueAttributeName = "Id";
            this.cbProperty.AttributeName = "PropertyId";
            this.cbProperty.ContextName = "DialogContext";
            this.cbProperty.DomainName = "DynamicProperty";
            this.table2.Add(this.cbProperty);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table2[this.cbProperty]));
            w5.TopAttach = ((uint)(1));
            w5.BottomAttach = ((uint)(2));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lblApplication = new Gtk.Label();
            this.lblApplication.Name = "lblApplication";
            this.lblApplication.Xalign = 0F;
            this.lblApplication.LabelProp = Mono.Unix.Catalog.GetString("Application:");
            this.table2.Add(this.lblApplication);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table2[this.lblApplication]));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lblDefaultValue = new Gtk.Label();
            this.lblDefaultValue.Name = "lblDefaultValue";
            this.lblDefaultValue.Xalign = 0F;
            this.lblDefaultValue.LabelProp = Mono.Unix.Catalog.GetString("Default Value:");
            this.table2.Add(this.lblDefaultValue);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table2[this.lblDefaultValue]));
            w7.TopAttach = ((uint)(3));
            w7.BottomAttach = ((uint)(4));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lblProperty = new Gtk.Label();
            this.lblProperty.Name = "lblProperty";
            this.lblProperty.Xalign = 0F;
            this.lblProperty.LabelProp = Mono.Unix.Catalog.GetString("Property:");
            this.table2.Add(this.lblProperty);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table2[this.lblProperty]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.lblQualifier = new Gtk.Label();
            this.lblQualifier.Name = "lblQualifier";
            this.lblQualifier.Xalign = 0F;
            this.lblQualifier.LabelProp = Mono.Unix.Catalog.GetString("Qualifier:");
            this.table2.Add(this.lblQualifier);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table2[this.lblQualifier]));
            w9.TopAttach = ((uint)(2));
            w9.BottomAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.txtDefaultValue = new ControlWrappers.BoundEntry();
            this.txtDefaultValue.Events = ((Gdk.EventMask)(256));
            this.txtDefaultValue.Name = "txtDefaultValue";
            this.txtDefaultValue.IsEditable = true;
            this.txtDefaultValue.ActivatesDefault = false;
            this.txtDefaultValue.AttributeName = "DefaultValue";
            this.txtDefaultValue.ContextName = "DialogContext";
            this.txtDefaultValue.DomainName = "DynamicProperty";
            this.table2.Add(this.txtDefaultValue);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table2[this.txtDefaultValue]));
            w10.TopAttach = ((uint)(3));
            w10.BottomAttach = ((uint)(4));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table2.Gtk.Table+TableChild
            this.txtQualifier = new ControlWrappers.BoundEntry();
            this.txtQualifier.Events = ((Gdk.EventMask)(256));
            this.txtQualifier.Name = "txtQualifier";
            this.txtQualifier.IsEditable = true;
            this.txtQualifier.ActivatesDefault = false;
            this.txtQualifier.AttributeName = "Qualifier";
            this.txtQualifier.ContextName = "DialogContext";
            this.txtQualifier.DomainName = "DynamicProperty";
            this.table2.Add(this.txtQualifier);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.table2[this.txtQualifier]));
            w11.TopAttach = ((uint)(2));
            w11.BottomAttach = ((uint)(3));
            w11.LeftAttach = ((uint)(1));
            w11.RightAttach = ((uint)(2));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table2);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox2[this.table2]));
            w12.Position = 0;
            w12.Expand = false;
            w12.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table3 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table3.Name = "table3";
            this.table3.RowSpacing = ((uint)(6));
            this.table3.ColumnSpacing = ((uint)(6));
            // Container child table3.Gtk.Table+TableChild
            this.btnBoxApplySettings = new Gtk.HButtonBox();
            this.btnBoxApplySettings.Name = "btnBoxApplySettings";
            this.table3.Add(this.btnBoxApplySettings);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table3[this.btnBoxApplySettings]));
            w13.TopAttach = ((uint)(2));
            w13.BottomAttach = ((uint)(3));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.hbuttonbox2 = new Gtk.HButtonBox();
            this.hbuttonbox2.Name = "hbuttonbox2";
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.btnAddItem = new Gtk.Button();
            this.btnAddItem.Sensitive = false;
            this.btnAddItem.CanFocus = true;
            this.btnAddItem.Name = "btnAddItem";
            this.btnAddItem.UseStock = true;
            this.btnAddItem.UseUnderline = true;
            this.btnAddItem.Label = "gtk-add";
            this.hbuttonbox2.Add(this.btnAddItem);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnAddItem]));
            w14.Expand = false;
            w14.Fill = false;
            // Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
            this.btnRemove = new Gtk.Button();
            this.btnRemove.Sensitive = false;
            this.btnRemove.CanFocus = true;
            this.btnRemove.Name = "btnRemove";
            this.btnRemove.UseStock = true;
            this.btnRemove.UseUnderline = true;
            this.btnRemove.Label = "gtk-remove";
            this.hbuttonbox2.Add(this.btnRemove);
            Gtk.ButtonBox.ButtonBoxChild w15 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnRemove]));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            this.table3.Add(this.hbuttonbox2);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table3[this.hbuttonbox2]));
            w16.TopAttach = ((uint)(2));
            w16.BottomAttach = ((uint)(3));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.lblEffectiveValues = new Gtk.Label();
            this.lblEffectiveValues.Name = "lblEffectiveValues";
            this.lblEffectiveValues.Xalign = 0F;
            this.lblEffectiveValues.LabelProp = Mono.Unix.Catalog.GetString("Effective Values:");
            this.table3.Add(this.lblEffectiveValues);
            Gtk.Table.TableChild w17 = ((Gtk.Table.TableChild)(this.table3[this.lblEffectiveValues]));
            w17.XOptions = ((Gtk.AttachOptions)(4));
            w17.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.nbValuePages = new Gtk.Notebook();
            this.nbValuePages.CanFocus = true;
            this.nbValuePages.Name = "nbValuePages";
            this.nbValuePages.CurrentPage = 1;
            this.nbValuePages.ShowTabs = false;
            // Container child nbValuePages.Gtk.Notebook+NotebookChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Nothing Selected");
            this.nbValuePages.Add(this.label2);
            // Notebook tab
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("page3");
            this.nbValuePages.SetTabLabel(this.label2, this.label1);
            this.label1.ShowAll();
            // Container child nbValuePages.Gtk.Notebook+NotebookChild
            this.table4 = new Gtk.Table(((uint)(2)), ((uint)(2)), false);
            this.table4.Name = "table4";
            this.table4.RowSpacing = ((uint)(6));
            this.table4.ColumnSpacing = ((uint)(6));
            this.table4.BorderWidth = ((uint)(6));
            // Container child table4.Gtk.Table+TableChild
            this.calEndDate = new ControlWrappers.BoundCalendar();
            this.calEndDate.Events = ((Gdk.EventMask)(256));
            this.calEndDate.Name = "calEndDate";
            this.calEndDate.Date = new System.DateTime(0);
            this.calEndDate.AttributeName = "EffectiveEndDate";
            this.calEndDate.ContextName = "EffectiveDateCtx";
            this.calEndDate.DomainName = "EffectiveValue";
            this.table4.Add(this.calEndDate);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table4[this.calEndDate]));
            w19.TopAttach = ((uint)(1));
            w19.BottomAttach = ((uint)(2));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.calStartDate = new ControlWrappers.BoundCalendar();
            this.calStartDate.Events = ((Gdk.EventMask)(256));
            this.calStartDate.Name = "calStartDate";
            this.calStartDate.Date = new System.DateTime(0);
            this.calStartDate.AttributeName = "EffectiveStartDate";
            this.calStartDate.ContextName = "EffectiveDateCtx";
            this.calStartDate.DomainName = "EffectiveValue";
            this.table4.Add(this.calStartDate);
            Gtk.Table.TableChild w20 = ((Gtk.Table.TableChild)(this.table4[this.calStartDate]));
            w20.TopAttach = ((uint)(1));
            w20.BottomAttach = ((uint)(2));
            w20.XOptions = ((Gtk.AttachOptions)(4));
            w20.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblEndDate = new Gtk.Label();
            this.lblEndDate.Name = "lblEndDate";
            this.lblEndDate.Xalign = 0F;
            this.lblEndDate.LabelProp = Mono.Unix.Catalog.GetString("End Date:");
            this.table4.Add(this.lblEndDate);
            Gtk.Table.TableChild w21 = ((Gtk.Table.TableChild)(this.table4[this.lblEndDate]));
            w21.LeftAttach = ((uint)(1));
            w21.RightAttach = ((uint)(2));
            w21.XOptions = ((Gtk.AttachOptions)(4));
            w21.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table4.Gtk.Table+TableChild
            this.lblStartDate = new Gtk.Label();
            this.lblStartDate.Name = "lblStartDate";
            this.lblStartDate.Xalign = 0F;
            this.lblStartDate.LabelProp = Mono.Unix.Catalog.GetString("Start Date:");
            this.table4.Add(this.lblStartDate);
            Gtk.Table.TableChild w22 = ((Gtk.Table.TableChild)(this.table4[this.lblStartDate]));
            w22.XOptions = ((Gtk.AttachOptions)(4));
            w22.YOptions = ((Gtk.AttachOptions)(4));
            this.nbValuePages.Add(this.table4);
            Gtk.Notebook.NotebookChild w23 = ((Gtk.Notebook.NotebookChild)(this.nbValuePages[this.table4]));
            w23.Position = 1;
            // Notebook tab
            this.label6 = new Gtk.Label();
            this.label6.Name = "label6";
            this.label6.LabelProp = Mono.Unix.Catalog.GetString("Effective Value");
            this.nbValuePages.SetTabLabel(this.table4, this.label6);
            this.label6.ShowAll();
            // Container child nbValuePages.Gtk.Notebook+NotebookChild
            this.table5 = new Gtk.Table(((uint)(8)), ((uint)(5)), false);
            this.table5.Name = "table5";
            this.table5.RowSpacing = ((uint)(6));
            this.table5.ColumnSpacing = ((uint)(6));
            this.table5.BorderWidth = ((uint)(6));
            // Container child table5.Gtk.Table+TableChild
            this.lblCriteria = new Gtk.Label();
            this.lblCriteria.Name = "lblCriteria";
            this.lblCriteria.Xalign = 0F;
            this.lblCriteria.LabelProp = Mono.Unix.Catalog.GetString("Criteria:");
            this.table5.Add(this.lblCriteria);
            Gtk.Table.TableChild w24 = ((Gtk.Table.TableChild)(this.table5[this.lblCriteria]));
            w24.TopAttach = ((uint)(4));
            w24.BottomAttach = ((uint)(5));
            w24.RightAttach = ((uint)(5));
            w24.XOptions = ((Gtk.AttachOptions)(4));
            w24.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblDays = new Gtk.Label();
            this.lblDays.Name = "lblDays";
            this.lblDays.Xalign = 0F;
            this.lblDays.LabelProp = Mono.Unix.Catalog.GetString("Days:");
            this.table5.Add(this.lblDays);
            Gtk.Table.TableChild w25 = ((Gtk.Table.TableChild)(this.table5[this.lblDays]));
            w25.LeftAttach = ((uint)(2));
            w25.RightAttach = ((uint)(3));
            w25.XOptions = ((Gtk.AttachOptions)(4));
            w25.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblDOWs = new Gtk.Label();
            this.lblDOWs.Name = "lblDOWs";
            this.lblDOWs.Xalign = 0F;
            this.lblDOWs.LabelProp = Mono.Unix.Catalog.GetString("DOW:");
            this.table5.Add(this.lblDOWs);
            Gtk.Table.TableChild w26 = ((Gtk.Table.TableChild)(this.table5[this.lblDOWs]));
            w26.LeftAttach = ((uint)(4));
            w26.RightAttach = ((uint)(5));
            w26.XOptions = ((Gtk.AttachOptions)(4));
            w26.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblHours = new Gtk.Label();
            this.lblHours.Name = "lblHours";
            this.lblHours.Xalign = 0F;
            this.lblHours.LabelProp = Mono.Unix.Catalog.GetString("Hours:");
            this.table5.Add(this.lblHours);
            Gtk.Table.TableChild w27 = ((Gtk.Table.TableChild)(this.table5[this.lblHours]));
            w27.LeftAttach = ((uint)(1));
            w27.RightAttach = ((uint)(2));
            w27.XOptions = ((Gtk.AttachOptions)(4));
            w27.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblMinutes = new Gtk.Label();
            this.lblMinutes.Name = "lblMinutes";
            this.lblMinutes.Xalign = 0F;
            this.lblMinutes.LabelProp = Mono.Unix.Catalog.GetString("Minutes:");
            this.table5.Add(this.lblMinutes);
            Gtk.Table.TableChild w28 = ((Gtk.Table.TableChild)(this.table5[this.lblMinutes]));
            w28.XOptions = ((Gtk.AttachOptions)(4));
            w28.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblMonths = new Gtk.Label();
            this.lblMonths.Name = "lblMonths";
            this.lblMonths.Xalign = 0F;
            this.lblMonths.LabelProp = Mono.Unix.Catalog.GetString("Months:");
            this.table5.Add(this.lblMonths);
            Gtk.Table.TableChild w29 = ((Gtk.Table.TableChild)(this.table5[this.lblMonths]));
            w29.LeftAttach = ((uint)(3));
            w29.RightAttach = ((uint)(4));
            w29.XOptions = ((Gtk.AttachOptions)(4));
            w29.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.lblValue = new Gtk.Label();
            this.lblValue.Name = "lblValue";
            this.lblValue.Xalign = 0F;
            this.lblValue.LabelProp = Mono.Unix.Catalog.GetString("Value:");
            this.table5.Add(this.lblValue);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table5[this.lblValue]));
            w30.TopAttach = ((uint)(6));
            w30.BottomAttach = ((uint)(7));
            w30.RightAttach = ((uint)(5));
            w30.XOptions = ((Gtk.AttachOptions)(4));
            w30.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.tvDays = new ControlWrappers.CronValueEditor();
            this.tvDays.Events = ((Gdk.EventMask)(256));
            this.tvDays.Name = "tvDays";
            this.tvDays.ValueType = 2;
            this.table5.Add(this.tvDays);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table5[this.tvDays]));
            w31.TopAttach = ((uint)(1));
            w31.BottomAttach = ((uint)(4));
            w31.LeftAttach = ((uint)(2));
            w31.RightAttach = ((uint)(3));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.tvDaysOfWeek = new ControlWrappers.CronValueEditor();
            this.tvDaysOfWeek.Events = ((Gdk.EventMask)(256));
            this.tvDaysOfWeek.Name = "tvDaysOfWeek";
            this.tvDaysOfWeek.ValueType = 4;
            this.table5.Add(this.tvDaysOfWeek);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table5[this.tvDaysOfWeek]));
            w32.TopAttach = ((uint)(1));
            w32.BottomAttach = ((uint)(4));
            w32.LeftAttach = ((uint)(4));
            w32.RightAttach = ((uint)(5));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.tvHours = new ControlWrappers.CronValueEditor();
            this.tvHours.Events = ((Gdk.EventMask)(256));
            this.tvHours.Name = "tvHours";
            this.tvHours.ValueType = 1;
            this.table5.Add(this.tvHours);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table5[this.tvHours]));
            w33.TopAttach = ((uint)(1));
            w33.BottomAttach = ((uint)(4));
            w33.LeftAttach = ((uint)(1));
            w33.RightAttach = ((uint)(2));
            w33.XOptions = ((Gtk.AttachOptions)(4));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.tvMinutes = new ControlWrappers.CronValueEditor();
            this.tvMinutes.HeightRequest = 200;
            this.tvMinutes.Events = ((Gdk.EventMask)(256));
            this.tvMinutes.Name = "tvMinutes";
            this.tvMinutes.ValueType = 0;
            this.table5.Add(this.tvMinutes);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table5[this.tvMinutes]));
            w34.TopAttach = ((uint)(1));
            w34.BottomAttach = ((uint)(4));
            w34.XOptions = ((Gtk.AttachOptions)(4));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.tvMonths = new ControlWrappers.CronValueEditor();
            this.tvMonths.Events = ((Gdk.EventMask)(256));
            this.tvMonths.Name = "tvMonths";
            this.tvMonths.ValueType = 3;
            this.table5.Add(this.tvMonths);
            Gtk.Table.TableChild w35 = ((Gtk.Table.TableChild)(this.table5[this.tvMonths]));
            w35.TopAttach = ((uint)(1));
            w35.BottomAttach = ((uint)(4));
            w35.LeftAttach = ((uint)(3));
            w35.RightAttach = ((uint)(4));
            w35.XOptions = ((Gtk.AttachOptions)(4));
            w35.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.txtCriteria = new ControlWrappers.BoundEntry();
            this.txtCriteria.Events = ((Gdk.EventMask)(256));
            this.txtCriteria.Name = "txtCriteria";
            this.txtCriteria.IsEditable = false;
            this.txtCriteria.ActivatesDefault = false;
            this.txtCriteria.AttributeName = "RawCriteria";
            this.txtCriteria.ContextName = "ValueCriteriaCtx";
            this.txtCriteria.DomainName = "ValueCriteria";
            this.table5.Add(this.txtCriteria);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table5[this.txtCriteria]));
            w36.TopAttach = ((uint)(5));
            w36.BottomAttach = ((uint)(6));
            w36.RightAttach = ((uint)(5));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table5.Gtk.Table+TableChild
            this.txtValue = new ControlWrappers.BoundEntry();
            this.txtValue.Events = ((Gdk.EventMask)(256));
            this.txtValue.Name = "txtValue";
            this.txtValue.IsEditable = true;
            this.txtValue.ActivatesDefault = false;
            this.txtValue.AttributeName = "Value";
            this.txtValue.ContextName = "ValueCriteriaCtx";
            this.txtValue.DomainName = "ValueCriteria";
            this.table5.Add(this.txtValue);
            Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table5[this.txtValue]));
            w37.TopAttach = ((uint)(7));
            w37.BottomAttach = ((uint)(8));
            w37.RightAttach = ((uint)(5));
            w37.XOptions = ((Gtk.AttachOptions)(4));
            w37.YOptions = ((Gtk.AttachOptions)(4));
            this.nbValuePages.Add(this.table5);
            Gtk.Notebook.NotebookChild w38 = ((Gtk.Notebook.NotebookChild)(this.nbValuePages[this.table5]));
            w38.Position = 2;
            // Notebook tab
            this.label7 = new Gtk.Label();
            this.label7.Name = "label7";
            this.label7.LabelProp = Mono.Unix.Catalog.GetString("Value Criteria");
            this.nbValuePages.SetTabLabel(this.table5, this.label7);
            this.label7.ShowAll();
            this.table3.Add(this.nbValuePages);
            Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table3[this.nbValuePages]));
            w39.TopAttach = ((uint)(1));
            w39.BottomAttach = ((uint)(2));
            w39.LeftAttach = ((uint)(1));
            w39.RightAttach = ((uint)(2));
            w39.XOptions = ((Gtk.AttachOptions)(4));
            w39.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table3.Gtk.Table+TableChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.tvEffectiveValues = new Gtk.TreeView();
            this.tvEffectiveValues.WidthRequest = 300;
            this.tvEffectiveValues.CanFocus = true;
            this.tvEffectiveValues.Name = "tvEffectiveValues";
            this.tvEffectiveValues.EnableSearch = false;
            this.tvEffectiveValues.HeadersVisible = false;
            this.scrolledwindow1.Add(this.tvEffectiveValues);
            this.table3.Add(this.scrolledwindow1);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table3[this.scrolledwindow1]));
            w41.TopAttach = ((uint)(1));
            w41.BottomAttach = ((uint)(2));
            w41.XOptions = ((Gtk.AttachOptions)(4));
            w41.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table3);
            Gtk.Box.BoxChild w42 = ((Gtk.Box.BoxChild)(this.vbox2[this.table3]));
            w42.Position = 1;
            w42.Expand = false;
            w42.Fill = false;
            w2.Add(this.vbox2);
            Gtk.Box.BoxChild w43 = ((Gtk.Box.BoxChild)(w2[this.vbox2]));
            w43.Position = 0;
            w43.Expand = false;
            w43.Fill = false;
            // Internal child PropertyManager.DynPropEntryDlg.ActionArea
            Gtk.HButtonBox w44 = this.ActionArea;
            w44.Name = "dialog1_ActionArea";
            w44.Spacing = 6;
            w44.BorderWidth = ((uint)(5));
            w44.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w45 = ((Gtk.ButtonBox.ButtonBoxChild)(w44[this.buttonCancel]));
            w45.Expand = false;
            w45.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w46 = ((Gtk.ButtonBox.ButtonBoxChild)(w44[this.buttonOk]));
            w46.Position = 1;
            w46.Expand = false;
            w46.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 804;
            this.DefaultHeight = 606;
            this.Show();
            this.cbForm.Changed += new System.EventHandler(this.OnCbFormChanged);
            this.tvEffectiveValues.CursorChanged += new System.EventHandler(this.EffectiveValueCursorChanged);
            this.calStartDate.DateTimeChanged += new System.EventHandler(this.StartDateChanged);
            this.calEndDate.DateTimeChanged += new System.EventHandler(this.EndDateChanged);
            this.txtValue.Changed += new System.EventHandler(this.VCValueChanged);
            this.tvMonths.Changed += new System.EventHandler(this.MonthsEditorChanged);
            this.tvMinutes.Changed += new System.EventHandler(this.MinutesEditorChanged);
            this.tvHours.Changed += new System.EventHandler(this.HoursEditorChanged);
            this.tvDaysOfWeek.Changed += new System.EventHandler(this.DaysOfWeekEditorChanged);
            this.tvDays.Changed += new System.EventHandler(this.DaysEditorChanged);
            this.btnAddItem.Clicked += new System.EventHandler(this.AddItemClicked);
            this.btnRemove.Clicked += new System.EventHandler(this.RemoveItemClicked);
        }
    }
}
