// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PropertyManager {
    
    
    public partial class ApplicationEntryDlg {
        
        private Gtk.Table table1;
        
        private Gtk.Label lblApplicationName;
        
        private ControlWrappers.BoundEntry txtApplicationName;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PropertyManager.ApplicationEntryDlg
            this.Name = "PropertyManager.ApplicationEntryDlg";
            this.Title = Mono.Unix.Catalog.GetString("Application Details");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child PropertyManager.ApplicationEntryDlg.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(1)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.lblApplicationName = new Gtk.Label();
            this.lblApplicationName.Name = "lblApplicationName";
            this.lblApplicationName.LabelProp = Mono.Unix.Catalog.GetString("Application Name:");
            this.table1.Add(this.lblApplicationName);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.lblApplicationName]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtApplicationName = new ControlWrappers.BoundEntry();
            this.txtApplicationName.Events = ((Gdk.EventMask)(256));
            this.txtApplicationName.Name = "txtApplicationName";
            this.txtApplicationName.IsEditable = true;
            this.txtApplicationName.ActivatesDefault = true;
            this.txtApplicationName.AttributeName = "Name";
            this.txtApplicationName.ContextName = "DialogContext";
            this.txtApplicationName.DomainName = "Application";
            this.table1.Add(this.txtApplicationName);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.txtApplicationName]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Internal child PropertyManager.ApplicationEntryDlg.ActionArea
            Gtk.HButtonBox w5 = this.ActionArea;
            w5.Name = "dialog1_ActionArea";
            w5.Spacing = 6;
            w5.BorderWidth = ((uint)(5));
            w5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonCancel]));
            w6.Expand = false;
            w6.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.buttonOk]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 391;
            this.DefaultHeight = 91;
            this.buttonOk.HasDefault = true;
            this.Show();
        }
    }
}
