// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace PropertyManager {
    
    
    public partial class PropertyDefinitionEntryDlg {
        
        private Gtk.Table table1;
        
        private Gtk.ComboBox cbDataType;
        
        private Gtk.Label lblCategory;
        
        private Gtk.Label lblDataType;
        
        private Gtk.Label lblDescription;
        
        private Gtk.Label lblName;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private Gtk.TextView tvDescription;
        
        private Gtk.Entry txtCategories;
        
        private Gtk.Entry txtName;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget PropertyManager.PropertyDefinitionEntryDlg
            this.Name = "PropertyManager.PropertyDefinitionEntryDlg";
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.HasSeparator = false;
            // Internal child PropertyManager.PropertyDefinitionEntryDlg.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(6)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.cbDataType = Gtk.ComboBox.NewText();
            this.cbDataType.Name = "cbDataType";
            this.table1.Add(this.cbDataType);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.cbDataType]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblCategory = new Gtk.Label();
            this.lblCategory.Name = "lblCategory";
            this.lblCategory.LabelProp = Mono.Unix.Catalog.GetString("Category:");
            this.table1.Add(this.lblCategory);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.lblCategory]));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblDataType = new Gtk.Label();
            this.lblDataType.Name = "lblDataType";
            this.lblDataType.LabelProp = Mono.Unix.Catalog.GetString("Data Type:");
            this.table1.Add(this.lblDataType);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.lblDataType]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblDescription = new Gtk.Label();
            this.lblDescription.Name = "lblDescription";
            this.lblDescription.Xalign = 0F;
            this.lblDescription.LabelProp = Mono.Unix.Catalog.GetString("Description:");
            this.table1.Add(this.lblDescription);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.lblDescription]));
            w5.TopAttach = ((uint)(3));
            w5.BottomAttach = ((uint)(4));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.lblName = new Gtk.Label();
            this.lblName.Name = "lblName";
            this.lblName.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.table1.Add(this.lblName);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.lblName]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.tvDescription = new Gtk.TextView();
            this.tvDescription.CanFocus = true;
            this.tvDescription.Name = "tvDescription";
            this.tvDescription.LeftMargin = 10;
            this.tvDescription.RightMargin = 10;
            this.scrolledwindow1.Add(this.tvDescription);
            this.table1.Add(this.scrolledwindow1);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.table1[this.scrolledwindow1]));
            w8.TopAttach = ((uint)(4));
            w8.BottomAttach = ((uint)(6));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(0));
            w8.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table1.Gtk.Table+TableChild
            this.txtCategories = new Gtk.Entry();
            this.txtCategories.CanFocus = true;
            this.txtCategories.Name = "txtCategories";
            this.txtCategories.IsEditable = true;
            this.txtCategories.InvisibleChar = '●';
            this.table1.Add(this.txtCategories);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.txtCategories]));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.txtName = new Gtk.Entry();
            this.txtName.CanFocus = true;
            this.txtName.Name = "txtName";
            this.txtName.IsEditable = true;
            this.txtName.InvisibleChar = '●';
            this.table1.Add(this.txtName);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.txtName]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(1));
            w10.RightAttach = ((uint)(2));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w11.Position = 0;
            // Internal child PropertyManager.PropertyDefinitionEntryDlg.ActionArea
            Gtk.HButtonBox w12 = this.ActionArea;
            w12.Name = "dialog1_ActionArea";
            w12.Spacing = 6;
            w12.BorderWidth = ((uint)(5));
            w12.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w13 = ((Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonCancel]));
            w13.Expand = false;
            w13.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w14 = ((Gtk.ButtonBox.ButtonBoxChild)(w12[this.buttonOk]));
            w14.Position = 1;
            w14.Expand = false;
            w14.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 364;
            this.DefaultHeight = 325;
            this.Show();
        }
    }
}
