INSERT INTO DYN_APPLICATION (
       DYN_APPLICATION_ID, APPLICATION_NAME
) VALUES (
  1, 'Online'
);

INSERT INTO DYN_APPLICATION (
       DYN_APPLICATION_ID, APPLICATION_NAME
) VALUES (
  2, 'BP'
);

INSERT INTO DYN_APPLICATION (
       DYN_APPLICATION_ID, APPLICATION_NAME
) VALUES (
  3, 'DE'
);

INSERT INTO DYN_APPLICATION (
       DYN_APPLICATION_ID, APPLICATION_NAME
) VALUES (
  4, 'CAS'
);

